package com.vsk.employee_management_webapp.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor; // Make sure this is present
import lombok.AllArgsConstructor; // Add this if you want an all-args constructor generated by Lombok too

@Entity
@Table(name = "employees")
@Getter
@Setter
@NoArgsConstructor // Lombok will generate a no-argument constructor
// @AllArgsConstructor // You can add this if you want Lombok to generate a constructor with all fields
public class Employee {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Column(name = "first_name")
    private String firstName;

    @Column(name = "last_name")
    private String lastName;

    @Column(name = "email")
    private String email;

    // Explicit constructor for creating new Employee objects with details
    public Employee(String firstName, String lastName, String email) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }
}